### ISSUE TITLE
Imagen que no funciona

### ISSUE THREAD

**Issue by JoseDRojasA** [destroucs/FindMyRoom#1]
Estuve probando la app pero no aparece una imagen ubicada en la parte superior derecha

**Comment by JoseDRojasA** [comment]
La solución es la siguiente:
Añada la siguiente etiqueta en "head".

`<base href="/FindMyRoom/" target="_blank">`

Y cambie la la ruta "/dist" por "dist"

**Comment by JuanDiegoLopez** [comment]
Gracias Josefis!
