### ISSUE TITLE
Ubicación de footer

### ISSUE THREAD

**Issue by JoseDRojasA** [destroucs/FindMyRoom#2]
El footer en pantallas muy grandes (1920x1080) no aparece al final de la pantalla

**Comment by JoseDRojasA** [comment]
Mire negrito, ahi le dejo la solución:

En el div con id "app", añadir el siguiente estilo:
`min-height: 100vh;`

En la clase "page-footer"

`    position: relative;
    bottom: 0px;
    width: 100%;`

**Comment by JuanDiegoLopez** [comment]
Esa solución no funciono. Después de buscar exhaustivamente encontré por mi propia cuenta esta.
```#app {  display:grid; min-heigth: 100vh; }```
Gracias de todas formas.
